version: '3.5'

services:

  db:
    image: mysql:5.7
    container_name: wp-context-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'wp-context'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./test/integration/container/Dockerfile
    container_name: wp-context-wordpress
    restart: always
    ports:
      - '8151:80'
    volumes:
      - ./src:/var/www/html/wp-content/plugins/wp-context/src
      - ./test/integration:/var/www/html/wp-content/plugins/wp-context/test/integration
      - ./vendor:/var/www/html/wp-content/plugins/wp-context/vendor
      - ./composer.json:/var/www/html/wp-content/plugins/wp-context/composer.json
      - ./test/integration/container/index.php:/var/www/html/wp-content/plugins/wp-context/index.php
    environment:
      WP_DB_HOST: 'db:3306'
      WP_DB_NAME: 'wp-context'
      WP_DB_USER: 'root'
      WP_DB_PASS: 'root'
      WP_ADMIN_USER: 'admin'
      WP_ADMIN_PASS: 'z'
      WP_URL: 'http://localhost:8151'
      EXTRA_PHP: |
        define('WP_DISABLE_FATAL_ERROR_HANDLER', true);
        define('WP_DEBUG', true);
        define('FS_METHOD', 'direct');
